### ISSUE TITLE
DB open error (MDBX “unknown error code: 11”) when running rbuilder separately from reth

### ISSUE THREAD

**Issue by iowar** [flashbots/rbuilder#484]
I'm encountering a recurring DB open error when running rbuilder as a separate container alongside reth. My setup mounts the Reth database directory (and IPC path) into the RBuilder container in read-only mode. However, I keep getting the following error in the logs:
```
Error: DB open error

Caused by:
   0: Could not open database at path: /data/db
   1: failed to open the database: unknown error code: 11 (11)
```
appears that MDBX does not allow two separate processes (reth writing to the DB and rbuilder also opening the same DB) without conflict.

From what I understand from the documents, reth should be run as a separate process from rbuilder. Can someone explain exactly where I am making a mistake?

**Comment by ferranbt** [comment]
Can you share the commands and config that you are running?

**Comment by iowar** [comment]
sure..
``` 
 execution:
    image: ghcr.io/paradigmxyz/reth:latest
    environment:
      - RUST_LOG=info
    volumes:
      - ./data/reth/execution:/data
      - ./data/secrets:/secrets
    command:
      - "node"
      - "--chain=holesky"
      - "--datadir=/data"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.port=8545"
      - "--http.api=eth,net,web3,rpc,trace,txpool,debug"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.port=8546"
      - "--ws.api=eth,net,web3,rpc,trace,txpool,debug"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.jwtsecret=/secrets/jwtsecret"
      - "--ipcpath=/data/reth.ipc"
      - "-vvvv"
    healthcheck:
      test: ["CMD", "ls", "/data/reth.ipc"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  rbuilder:
    build:
      context: ./rbuilder
    environment:
      - BUILDER_SECRET_KEY=${BUILDER_SECRET_KEY}
      - RELAY_SECRET_KEY=${RELAY_SECRET_KEY}
      - OPTIMISTIC_RELAY_SECRET_KEY=${OPTIMISTIC_RELAY_SECRET_KEY}
      - CL_NODE_URL=http://lighthouse-beacon:3500
    volumes:
      - ./data/reth/execution:/data
      - ./rbuilder.toml:/config/rbuilder.toml

    command:
      - "run"
      - "/config/rbuilder.toml"
    depends_on:
      execution:
        condition: service_healthy
      lighthouse-beacon:
        condition: service_started
```

there is a Dockerfile in the rbuilder directory that compiles rbuilder for Docker,
and in rbuilder.toml, the following changes have been made:
`reth_datadir = "/data"` and `el_node_ipc_path = "/data/reth.ipc"`

**Comment by DarkArtistry** [comment]
my understanding is that, when you tried to run the rbuilder, it attempts to look at the database file and somehow even when i tried to run rbuilder using docker and mount the same virtual folder. it does not accepts because of permissions issues.. it will not allow an external compute to modify the files directly. 

I could only run the rbuilder using `cargo run` command. i raised this in chat too. haha.

**Comment by irfanshaik11** [comment]
hi, we're having the same issue, any ideas on this?

**Comment by nckdcrpt** [comment]
For those still having issues, you can make it work by setting the following flag in your docker-compose: `pid: "reth"`, or however you've named the pairing reth container. 

An example would look like this:
```yaml
services:
  rbuilder:
    image: rbuilder-image
    pid: "reth"
  reth:
    image: reth
...
```

For Kubernetes environments, this can be done by setting `shareProcessNamespace: true`.

The reason behind this is that all the processes in containerized environments are namespaced. This allows the kernel to think of the containers as belonging to the same namespace.

That being said, I don't think it's fixable by rbuilder (or that it should be fixed by it), but i'd be good to have it noted somewhere. 
cc @ferranbt
